struct Target
{
    unsigned long index;
    string message;
    octet replayFlag;
};
struct Replay
{
    octet recvFlag;
    string guid;
};
struct DataChunk {
    unsigned long long id;                   // 分片编号
    unsigned long long total_chunks;         // 总分片数
    sequence<octet> payload;       // 分片内容（如每片64KB）
    octet flag;
};
struct GrpcInfo
{
  string funName;
  unsigned long arg1;
  unsigned long arg2;
};
struct GrpcReplay
{
  unsigned long result;
};