// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DataDefine.cpp
 * This source file contains the implementation of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "DataDefine.h"

#include <fastcdr/Cdr.h>


#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>




Target::Target()
{
}

Target::~Target()
{
}

Target::Target(
        const Target& x)
{
    m_index = x.m_index;
    m_message = x.m_message;
    m_replayFlag = x.m_replayFlag;
}

Target::Target(
        Target&& x) noexcept
{
    m_index = x.m_index;
    m_message = std::move(x.m_message);
    m_replayFlag = x.m_replayFlag;
}

Target& Target::operator =(
        const Target& x)
{

    m_index = x.m_index;
    m_message = x.m_message;
    m_replayFlag = x.m_replayFlag;
    return *this;
}

Target& Target::operator =(
        Target&& x) noexcept
{

    m_index = x.m_index;
    m_message = std::move(x.m_message);
    m_replayFlag = x.m_replayFlag;
    return *this;
}

bool Target::operator ==(
        const Target& x) const
{
    return (m_index == x.m_index &&
           m_message == x.m_message &&
           m_replayFlag == x.m_replayFlag);
}

bool Target::operator !=(
        const Target& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void Target::index(
        uint32_t _index)
{
    m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t Target::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& Target::index()
{
    return m_index;
}


/*!
 * @brief This function copies the value in member message
 * @param _message New value to be copied in member message
 */
void Target::message(
        const std::string& _message)
{
    m_message = _message;
}

/*!
 * @brief This function moves the value in member message
 * @param _message New value to be moved in member message
 */
void Target::message(
        std::string&& _message)
{
    m_message = std::move(_message);
}

/*!
 * @brief This function returns a constant reference to member message
 * @return Constant reference to member message
 */
const std::string& Target::message() const
{
    return m_message;
}

/*!
 * @brief This function returns a reference to member message
 * @return Reference to member message
 */
std::string& Target::message()
{
    return m_message;
}


/*!
 * @brief This function sets a value in member replayFlag
 * @param _replayFlag New value for member replayFlag
 */
void Target::replayFlag(
        uint8_t _replayFlag)
{
    m_replayFlag = _replayFlag;
}

/*!
 * @brief This function returns the value of member replayFlag
 * @return Value of member replayFlag
 */
uint8_t Target::replayFlag() const
{
    return m_replayFlag;
}

/*!
 * @brief This function returns a reference to member replayFlag
 * @return Reference to member replayFlag
 */
uint8_t& Target::replayFlag()
{
    return m_replayFlag;
}




Replay::Replay()
{
}

Replay::~Replay()
{
}

Replay::Replay(
        const Replay& x)
{
    m_recvFlag = x.m_recvFlag;
    m_guid = x.m_guid;
}

Replay::Replay(
        Replay&& x) noexcept
{
    m_recvFlag = x.m_recvFlag;
    m_guid = std::move(x.m_guid);
}

Replay& Replay::operator =(
        const Replay& x)
{

    m_recvFlag = x.m_recvFlag;
    m_guid = x.m_guid;
    return *this;
}

Replay& Replay::operator =(
        Replay&& x) noexcept
{

    m_recvFlag = x.m_recvFlag;
    m_guid = std::move(x.m_guid);
    return *this;
}

bool Replay::operator ==(
        const Replay& x) const
{
    return (m_recvFlag == x.m_recvFlag &&
           m_guid == x.m_guid);
}

bool Replay::operator !=(
        const Replay& x) const
{
    return !(*this == x);
}

/*!
 * @brief This function sets a value in member recvFlag
 * @param _recvFlag New value for member recvFlag
 */
void Replay::recvFlag(
        uint8_t _recvFlag)
{
    m_recvFlag = _recvFlag;
}

/*!
 * @brief This function returns the value of member recvFlag
 * @return Value of member recvFlag
 */
uint8_t Replay::recvFlag() const
{
    return m_recvFlag;
}

/*!
 * @brief This function returns a reference to member recvFlag
 * @return Reference to member recvFlag
 */
uint8_t& Replay::recvFlag()
{
    return m_recvFlag;
}


/*!
 * @brief This function copies the value in member guid
 * @param _guid New value to be copied in member guid
 */
void Replay::guid(
        const std::string& _guid)
{
    m_guid = _guid;
}

/*!
 * @brief This function moves the value in member guid
 * @param _guid New value to be moved in member guid
 */
void Replay::guid(
        std::string&& _guid)
{
    m_guid = std::move(_guid);
}

/*!
 * @brief This function returns a constant reference to member guid
 * @return Constant reference to member guid
 */
const std::string& Replay::guid() const
{
    return m_guid;
}

/*!
 * @brief This function returns a reference to member guid
 * @return Reference to member guid
 */
std::string& Replay::guid()
{
    return m_guid;
}


// Include auxiliary functions like for serializing/deserializing.
#include "DataDefineCdrAux.ipp"

