// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file DataDefine.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef _FAST_DDS_GENERATED_DATADEFINE_H_
#define _FAST_DDS_GENERATED_DATADEFINE_H_

#include <array>
#include <bitset>
#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>
#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>



#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DATADEFINE_SOURCE)
#define DATADEFINE_DllAPI __declspec( dllexport )
#else
#define DATADEFINE_DllAPI __declspec( dllimport )
#endif // DATADEFINE_SOURCE
#else
#define DATADEFINE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DATADEFINE_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
class CdrSizeCalculator;
} // namespace fastcdr
} // namespace eprosima





/*!
 * @brief This class represents the structure Target defined by the user in the IDL file.
 * @ingroup DataDefine
 */
class Target
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Target();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Target();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target(
            const Target& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target(
            Target&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target& operator =(
            const Target& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Target that will be copied.
     */
    eProsima_user_DllExport Target& operator =(
            Target&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Target object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Target& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Target object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Target& x) const;

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index);

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const;

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index();


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message);

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message);

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const;

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message();


    /*!
     * @brief This function sets a value in member replayFlag
     * @param _replayFlag New value for member replayFlag
     */
    eProsima_user_DllExport void replayFlag(
            uint8_t _replayFlag);

    /*!
     * @brief This function returns the value of member replayFlag
     * @return Value of member replayFlag
     */
    eProsima_user_DllExport uint8_t replayFlag() const;

    /*!
     * @brief This function returns a reference to member replayFlag
     * @return Reference to member replayFlag
     */
    eProsima_user_DllExport uint8_t& replayFlag();

private:

    uint32_t m_index{0};
    std::string m_message;
    uint8_t m_replayFlag{0};

};


/*!
 * @brief This class represents the structure Replay defined by the user in the IDL file.
 * @ingroup DataDefine
 */
class Replay
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Replay();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Replay();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Replay that will be copied.
     */
    eProsima_user_DllExport Replay(
            const Replay& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Replay that will be copied.
     */
    eProsima_user_DllExport Replay(
            Replay&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Replay that will be copied.
     */
    eProsima_user_DllExport Replay& operator =(
            const Replay& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Replay that will be copied.
     */
    eProsima_user_DllExport Replay& operator =(
            Replay&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x Replay object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Replay& x) const;

    /*!
     * @brief Comparison operator.
     * @param x Replay object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Replay& x) const;

    /*!
     * @brief This function sets a value in member recvFlag
     * @param _recvFlag New value for member recvFlag
     */
    eProsima_user_DllExport void recvFlag(
            uint8_t _recvFlag);

    /*!
     * @brief This function returns the value of member recvFlag
     * @return Value of member recvFlag
     */
    eProsima_user_DllExport uint8_t recvFlag() const;

    /*!
     * @brief This function returns a reference to member recvFlag
     * @return Reference to member recvFlag
     */
    eProsima_user_DllExport uint8_t& recvFlag();


    /*!
     * @brief This function copies the value in member guid
     * @param _guid New value to be copied in member guid
     */
    eProsima_user_DllExport void guid(
            const std::string& _guid);

    /*!
     * @brief This function moves the value in member guid
     * @param _guid New value to be moved in member guid
     */
    eProsima_user_DllExport void guid(
            std::string&& _guid);

    /*!
     * @brief This function returns a constant reference to member guid
     * @return Constant reference to member guid
     */
    eProsima_user_DllExport const std::string& guid() const;

    /*!
     * @brief This function returns a reference to member guid
     * @return Reference to member guid
     */
    eProsima_user_DllExport std::string& guid();

private:

    uint8_t m_recvFlag{0};
    std::string m_guid;

};


/*!
 * @brief This class represents the structure DataChunk defined by the user in the IDL file.
 * @ingroup DataDefine
 */
class DataChunk
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport DataChunk();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~DataChunk();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk(
            const DataChunk& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk(
            DataChunk&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk& operator =(
            const DataChunk& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object DataChunk that will be copied.
     */
    eProsima_user_DllExport DataChunk& operator =(
            DataChunk&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x DataChunk object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const DataChunk& x) const;

    /*!
     * @brief Comparison operator.
     * @param x DataChunk object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const DataChunk& x) const;

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    eProsima_user_DllExport void id(
            uint64_t _id);

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    eProsima_user_DllExport uint64_t id() const;

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    eProsima_user_DllExport uint64_t& id();


    /*!
     * @brief This function sets a value in member total_chunks
     * @param _total_chunks New value for member total_chunks
     */
    eProsima_user_DllExport void total_chunks(
            uint64_t _total_chunks);

    /*!
     * @brief This function returns the value of member total_chunks
     * @return Value of member total_chunks
     */
    eProsima_user_DllExport uint64_t total_chunks() const;

    /*!
     * @brief This function returns a reference to member total_chunks
     * @return Reference to member total_chunks
     */
    eProsima_user_DllExport uint64_t& total_chunks();


    /*!
     * @brief This function copies the value in member payload
     * @param _payload New value to be copied in member payload
     */
    eProsima_user_DllExport void payload(
            const std::vector<uint8_t>& _payload);

    /*!
     * @brief This function moves the value in member payload
     * @param _payload New value to be moved in member payload
     */
    eProsima_user_DllExport void payload(
            std::vector<uint8_t>&& _payload);

    /*!
     * @brief This function returns a constant reference to member payload
     * @return Constant reference to member payload
     */
    eProsima_user_DllExport const std::vector<uint8_t>& payload() const;

    /*!
     * @brief This function returns a reference to member payload
     * @return Reference to member payload
     */
    eProsima_user_DllExport std::vector<uint8_t>& payload();


    /*!
     * @brief This function sets a value in member flag
     * @param _flag New value for member flag
     */
    eProsima_user_DllExport void flag(
            uint8_t _flag);

    /*!
     * @brief This function returns the value of member flag
     * @return Value of member flag
     */
    eProsima_user_DllExport uint8_t flag() const;

    /*!
     * @brief This function returns a reference to member flag
     * @return Reference to member flag
     */
    eProsima_user_DllExport uint8_t& flag();

private:

    uint64_t m_id{0};
    uint64_t m_total_chunks{0};
    std::vector<uint8_t> m_payload;
    uint8_t m_flag{0};

};

#endif // _FAST_DDS_GENERATED_DATADEFINE_H_



